<?php
/**
 * Overview, Affiliation, Publications, Research, Awards, Linkages, Supervision.
 */

/**
 * Helper that is used to create menu callbacks and blocks for the various elements.
 *
 * @param $enabled_only
 *   Boolean that determines whether all or only enabled elemnts should
 *   be returned.
 */
function faeprofile_elements($enabled_only = FALSE) {
  $elements = array(
    'overview' => t('Overview'),
    'affiliations' => t('Affiliation'),
    'publications' => t('Publications'),
    'research' => t('Research'),
    'awards' => t('Awards'),
    'linkages' => t('Linkages'),
    'supervision' => t('Supervision'),
    'information' => t('Information'),
    'contact' => t('Contact'),
    'qualifications' => t('Qualifications'),
  );

  if (!$enabled_only) {
    return $elements;
  }

  $enabled = array_filter(variable_get('faeprofile_elements', array()));

  return array_intersect_key($elements, $enabled);
}

/**
 * Helper to return a label for a given element.
 */
function faeprofile_element_label($element) {
  $elements = faeprofile_elements();
  return $elements[$element];
}

/**
 * Implements hook_init().
 */
function faeprofile_init() {
  drupal_add_css( drupal_get_path('module', 'faeprofile') . '/css/faeprofile.css');
}

/**
 * Implements hook_permission().
 */
function faeprofile_permission() {
  $permissions = array();

  $permissions['administer faeprofile'] = array(
    'title' => t('Administer FaE Profile'),
    'description' => t('Choose which FaE Profile tabs are shown on user profile pages.'),
  );

  foreach (faeprofile_elements() as $element => $label) {
    $permissions['view faeprofile ' . $element] = array(
      'title' => t('View FaE @label information', array('@label' => $label)),
      'description' => t('View Find an Expert @label information on user profiles', array('@label' => $label)),
    );
  }

  return $permissions;
}

/**
 * Implements hook_menu().
 */
function faeprofile_menu() {
  $items = array();
  $weight = 0;

  $items['admin/config/people/faeprofile'] = array(
    'title' => t('FaE Profile'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('faeprofile_settings_form'),
    'access arguments' => array('administer faeprofile'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'faeprofile.admin.inc',
  );

/*
  foreach (faeprofile_elements(TRUE) as $element => $label) {
    if ($element == 'overview' || $element == 'contact') {
      continue;
    }

    $function = 'faeprofile_page_' . $element;
    $items['user/%user/' . $element] = array(
      'title' => t('@element', array('@element' => $label)),
      'page callback' => $function,
      'page arguments' => array(1),
      'access callback' => 'faeprofile_user_access',
      'access arguments' => array('view faeprofile ' . $element, 1),
      'type' => MENU_LOCAL_TASK,
      'weight' => ++$weight,
      'file' => 'faeprofile.pages.inc',
    );
  }
*/

  // Auto assign supervision for users
  $items['admin/config/people/faeprofile/update'] = array(
    'title' => t('Update supervision statuses'),
    'page callback' => 'faeprofile_supervision_update',
    'access arguments' => array('administer faeprofile'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Access callback for faeprofile tabs.
 *
 * Return TRUE only if a user has the correct permission and the resource
 * is present.
 */
function faeprofile_user_access($permission, $account) {
  $access = user_access($permission);

  // Seperate check for the extra profile field.
  if ($permission == 'view faeprofile information') {
    $value = trim(strip_tags($account->field_profile_profile['und'][0]['value']));
    $resource = !empty($value);
  }
  else {
    $resource = !empty($account->field_fae_resource['und'][0]['url']);
  }

  return ($access && $resource);
}

/**
 * Implements hook_menu_alter().
 */
function faeprofile_menu_alter(&$items) {
  if (variable_get('faeprofile_main', 0)) {
    $items['user/%user/view']['title'] = t('Overview');
    $items['user/%user/edit']['weight'] = 10;
  }
}

/**
 * Implements hook_block_info().
 */
function faeprofile_block_info() {
  $blocks = array();
  $blocks['faeprofile'] = array(
    'info' =>  t('Fae Profile: Combined overview'),
  );
  foreach (faeprofile_elements() as $element => $label) {
    $blocks[$element]['info'] = t('Fae Profile: @element', array('@element' => $label));
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function faeprofile_block_view($delta) {
  // Only show on a user page.
  if ((arg(0) != 'user') && (count(arg()) < 2)) {
    return array();
  }

  module_load_include('inc', 'faeprofile', 'faeprofile.pages');
  $function = 'faeprofile_page_' . $delta;

  if (!function_exists($function)) {
    return array();
  }

  $account = menu_get_object('user');
  if (empty($account->field_fae_resource['und'][0]['url'])) {
    return array();
  }

  // Make the API call and return themed data.
  $content = call_user_func($function, $account);

  // We need to trim the content, so the block is hidden if all we got is
  // some stealth whitespace.
  $content = trim($content);

  if (empty($content)) {
    return array();
  }

  return array(
    'subject' => t('FaE Profile @delta', array('@delta' => ucwords($delta))),
    'content' => $content,
  );
}

/**
 * Implements hook_user_presave().
 */
function faeprofile_user_presave(&$edit, $account, $category) {
  if (!function_exists('uom_fae_api_person_supervision')) {
    return;
  }

  // If missing the user field that stores supervisor status...
  if (!isset($account->field_person_supervision)) {
    return;
  }

  // Load the supervisor status from FaE and set a flag on the user.
  if (!empty($account->field_fae_resource[LANGUAGE_NONE][0]['url'])) {
    $supervision = uom_fae_api_person_supervision($account->field_fae_resource[LANGUAGE_NONE][0]['url']);
    $edit['field_person_supervision']['und'][0]['value'] = (!empty($supervision) && $supervision['supervisor'] == 'Y') ? 1 : 0;
  }
}

/**
 * Implements hook_user_view().
 */
function faeprofile_user_view($account, $view_mode, $langcode) {

  module_load_include('inc', 'faeprofile', 'faeprofile.pages');

  if (!function_exists('faeprofile_page_overview')) {
    return;
  }

/*
  if (user_access('view faeprofile overview')) {
    $account->content['faeprofile_overview'] = array(
      '#type' => 'user_profile_item',
      '#markup' => faeprofile_page_overview($account),
      '#attributes' => array('class' => array('faeprofile-overview')),
      '#weight' => -10,
    );
  }
*/

	/* 
	 * Hide this, since we can aggregate info in the overview tab
	 * See http://cc.dev.arts.unimelb.edu.au/admin/config/people/faeprofile for example
	 */
  if (variable_get('faeprofile_information', 0) && user_access('view faeprofile information')) {
    $account->content['faeprofile_information'] = array(
      '#type' => 'user_profile_item',
      '#markup' => faeprofile_page_information($account),
      '#attributes' => array('class' => array('faeprofile-information')),
      '#weight' => -9,
    );
  }

}

/**
 * Implements template_preprocess_user_profile().
 *
 * Turn off all but the overview, if required.
 */
function faeprofile_preprocess_user_profile(&$variables) {
  if (!variable_get('faeprofile_main', 0)) {
    return;
  }

  foreach (element_children($variables['user_profile']) as $element) {
    if ($element != 'faeprofile_overview' && $element != 'faeprofile_information') {
      unset($variables['user_profile'][$element]);
    }
  }
}

/**
 * Implements hook_theme().
 */
function faeprofile_theme() {
  return array(
    'faeprofile_information' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-information',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_overview' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-overview',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_contact' => array(
      'variables' => array(
        'data' => array(
          'email' => '',
          'phone' => '',
          'webpage' => '',
          'room' => '',
          'building' => 'University of Melbourne',
          'supervisor' => 'N',
        ),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-contact',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_affiliations' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-affiliations',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_publications' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-publications',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_research' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-research',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_awards' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-awards',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_qualifications' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-qualifications',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_linkages' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-linkages',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_supervision' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-supervision',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_thumbnail' => array(
      'variables' => array(
        'thumbnail' => NULL,
				'actualFilePart' => NULL,
        'style' => 'medium'
      ),
    ),
		'faeprofile_image_markup' => array(
      'variables' => array(
        'path' => NULL,
      ),
    ),
    'faeprofile_affiliation' => array(
      'variables' => array(
        'affiliation' => NULL,
      ),
    ),
    'faeprofile_publication_default' => array(
      'variables' => array(
        'publication' => NULL,
      ),
    ),
		'faeprofile_publication_whole_book' => array(
      'variables' => array(
        'publication' => NULL,
      ),
    ),
		'faeprofile_publication_chapter' => array(
      'variables' => array(
        'publication' => NULL,
      ),
    ),
		'faeprofile_publication_journal' => array(
      'variables' => array(
        'publication' => NULL,
      ),
    ),
    'faeprofile_grant' => array(
      'variables' => array(
        'grant' => NULL,
      ),
    ),
    'faeprofile_award' => array(
      'variables' => array(
        'award' => NULL,
      ),
    ),
    'faeprofile_qualification' => array(
      'variables' => array(
        'qualification' => NULL,
      ),
    ),
    'faeprofile_linkage' => array(
      'variables' => array(
        'linkage' => NULL,
      ),
    ),
    'faeprofile_supervisor' => array(
      'variables' => array(
        'available' => 'N',
      ),
    ),
  );
}

/**
 * Create an image from a FaE resource URI.
 *
 * Get:  http://www.findanexpert.unimelb.edu.au/individual/image/thumbnail14551
 * Want: http://www.findanexpert.unimelb.edu.au/pictures/thumbnail14551picture.jpg
 */
/*
function theme_faeprofile_thumbnail($vars) {
  if (empty($vars['thumbnail'])) {
    return NULL;
  }
  $ret = preg_match('/^(http:\/\/[A-Za-z0-9\.-]+)\/individual\/image\/([a-z0-9]+)$/', $vars['thumbnail'], $matches);
  if (!$ret) {
    return NULL;
  }
  $image = $matches[1] . '/pictures/' . $matches[2] . 'picture.jpg';

	// It seems imagecache_external not able to flush/delete image files.
	//$output = theme('imagecache_external', array('path' => $image, 'style_name' => $vars['style']));
	$output = theme('faeprofile_image_markup', array('path' => $image));

	return $output;
}
*/


function theme_faeprofile_thumbnail($vars) {
  if (empty($vars['thumbnail'])) {
    return NULL;
  }

	if (empty($vars['actualFilePart'])) {
    return NULL;
  }

  $ret = preg_match('/^(http:\/\/[A-Za-z0-9\.-]+)\/individual\/image\/([a-z0-9]+)$/', $vars['thumbnail'], $matches);
  if (!$ret) {
    return NULL;
  }

  $image = $matches[1]. $vars['actualFilePart'];

  // It seems imagecache_external not able to flush/delete image files.
  $output = theme('faeprofile_image_markup', array('path' => $image));

  return $output;
}



function theme_faeprofile_image_markup($vars) {
	if(empty($vars['path'])) {
    return NULL;
  }	

	$markup = '<img src="'. $vars['path']. '" alt="" />';
	return $markup;	
}


/**
 * Theme a supervision status.
 */
function theme_faeprofile_supervisor($vars) {
  $available = $vars['available'];
  return ($vars['available'] == 'Y') ? t('<span class="faeprofile-supervisor-available">Available</span>') : t('<span class="faeprofile-supervisor-unavailable">Not available</span>');
}

/**
 * Theme a grant.
 */
function theme_faeprofile_grant($vars) {
  $output = t('<a href="!link">!title</a> (@scheme) awarded by @organisation', array(
    '!title' => $vars['grant']['grant'],
    '!link' => $vars['grant']['link'],
    '@scheme' => !empty($vars['grant']['scheme']) ? $vars['grant']['scheme'] . '.' : '',
    '@organisation' => $vars['grant']['organisation']
  ));

  if (!empty($vars['grant']['start'])) {
    $output .= t(' <span class="faeprofile-listDateTime">@start-@end</span>', array(
      '@start' => $vars['grant']['start'],
      '@end' => $vars['grant']['end'],
    ));
  }

  return $output;
}

/**
 * Theme an award.
 */
function theme_faeprofile_award($vars) {
  // If award label start with comma (year is missing at the start), remove it.
  // e.g. ", Institute for Aegean Prehistory"
  $title = ltrim($vars['award']['award'], ", ");

  $output = t('<a href="!link">!title</a>, @organisation', array(
    '!title' => $title,
    '!link' => $vars['award']['link'],
    '@organisation' => $vars['award']['organisation']
  ));

  if (!empty($vars['award']['year'])) {
    $output .= t(' <span class="faeprofile-listDateTime">@year</span>', array(
      '@year' => $vars['award']['year'],
    ));
  }

  return $output;
}

/**
 * Theme a linkage.
 */
function theme_faeprofile_linkage($vars) {
  return t('!organisation (@role)', array(
    '!organisation' => l($vars['linkage']['orgLabel'], $vars['linkage']['org']),
    '@role' => $vars['linkage']['roleLabel'],
  ));
}

/**
 * Theme an affiliation.
 */
function theme_faeprofile_affiliation($vars) {
  return t('@organisation. @role', array(
    '@organisation' => $vars['affiliation']['organisation'],
    '@role' => $vars['affiliation']['role']
  ));
}

/**
 * Theme a publication as default.
 */ 
function theme_faeprofile_publication_default($vars) {
	$output = ' ';

	$part_head = t('@author_text "<a href="!link">!title</a>". @editor_text <i>@parent</i> @publisher', array(
		'!title' => strip_tags($vars['publication']['title']),
		'@author_text' => !empty($vars['publication']['author_text']) ? strip_tags($vars['publication']['author_text']). '.' : '',
		'@editor_text' => !empty($vars['publication']['editor_text']) ? $vars['publication']['editor_text']. '.' : '',
		'!link' => $vars['publication']['link'],
		'@parent' => !empty($vars['publication']['parent']) ? strip_tags($vars['publication']['parent']). '.' : '',
		'@publisher' => !empty($vars['publication']['publisher']) ? $vars['publication']['publisher'] : '',
	));

	$part_year = t(', @year', array('@year' => $vars['publication']['year']));

	// Volume or edition
	if (!empty($vars['publication']['volume'])) {
		$part_edition = $vars['publication']['volume'];
	}
	else if (!empty($vars['publication']['edition'])) {
		$part_edition = $vars['publication']['edition'];
	}
	else {
		$part_edition = '';
	}

	// Page
	if (!empty($vars['publication']['page_start_end'])) {
		$page_start_end = t(' pp. @page_start_end', array('@page_start_end' => $vars['publication']['page_start_end']));
	}
	else {
		$page_start_end = '';
	}

	// Combine volume/edition with page
	$tmp_array = array($part_edition, $page_start_end);
	$combined_edition = implode(', ', array_filter($tmp_array));

	if(!empty($combined_edition)) {
		$combined_edition = t(', @combined_edition', array('@combined_edition' => $combined_edition));
	}
	else {
		$combined_edition = '';
	}

	// test
	$type_text = t(' @type_text', array('@type_text' => $vars['publication']['type_text']));
	//$output = $part_head. $part_year. $combined_edition. $type_text;	
	$output = $part_head. $part_year. $combined_edition;

	return $output;	
}

// 
function theme_faeprofile_publication_whole_book($vars) {
	$output = ' ';	

	$part_head = t('@author_text <i><a href="!link">!title</a></i>. @publisher', array(
    '!title' => strip_tags($vars['publication']['title']),
    '@author_text' => !empty($vars['publication']['author_text']) ? strip_tags($vars['publication']['author_text']). '.' : '',
    '!link' => $vars['publication']['link'],
   	'@publisher' => !empty($vars['publication']['publisher']) ? $vars['publication']['publisher']. ',' : '', 
  ));

	//$part_year = t(' <span class="faeprofile-listDateTime">@year</span>', array('@year' => $vars['publication']['year']));
	$part_year = t(' @year', array('@year' => $vars['publication']['year']));
	
	$type_text = t(' @type_text', array('@type_text' => $vars['publication']['type_text']));

	//test
	$output = $part_head. $part_year; 
	//$output = $part_head. $part_year. $type_text;

	return $output;
}

//
function theme_faeprofile_publication_chapter($vars) {
  $output = ' ';

  $part_head = t('@author_text "<a href="!link">!title</a>". @editor_text <i>@parent</i> @publisher', array(
    '!title' => strip_tags($vars['publication']['title']),
    '@author_text' => !empty($vars['publication']['author_text']) ? strip_tags($vars['publication']['author_text']). '.' : '',
		'@editor_text' => !empty($vars['publication']['editor_text']) ? $vars['publication']['editor_text']. '.' : '',
    '!link' => $vars['publication']['link'],
    '@parent' => !empty($vars['publication']['parent']) ? strip_tags($vars['publication']['parent']). '.' : '',
    '@publisher' => !empty($vars['publication']['publisher']) ? $vars['publication']['publisher']. ',' : '',
  ));

  //$part_year = t(' <span class="faeprofile-listDateTime">@year</span>', array('@year' => $vars['publication']['year']));
	$part_year = t(' @year', array('@year' => $vars['publication']['year']));

	// Page
	if (!empty($vars['publication']['page_start_end'])) {
    $page_start_end = t(' pp. @page_start_end', array('@page_start_end' => $vars['publication']['page_start_end']));
  }
  else {
    $page_start_end = '';
  }

  $combined_edition = $page_start_end;
  $combined_edition = t(', @combined_edition', array('@combined_edition' => $combined_edition));

	$type_text = t(' @type_text', array('@type_text' => $vars['publication']['type_text']));

	//test
	//$output = $part_head. $part_year. $combined_edition. $type_text;
  $output = $part_head. $part_year. $combined_edition;

  return $output;
}

//
function theme_faeprofile_publication_journal($vars) {
	$output = '';

	$part_head = t('@author_text "<a href="!link">!title</a>". <i>@published_in</i>', array(
    '!title' => strip_tags($vars['publication']['title']),
    '@author_text' => !empty($vars['publication']['author_text']) ? strip_tags($vars['publication']['author_text']). '.' : '',
    '!link' => $vars['publication']['link'],
		'@published_in' => !empty($vars['publication']['publication']) ? strip_tags($vars['publication']['publication']). '.' : '',
    //'@publisher' => !empty($vars['publication']['publisher']) ? $vars['publication']['publisher'] : '',
  ));

	// Volume or edition
  if (!empty($vars['publication']['volume'])) {
    $part_edition = ' Vol. '. $vars['publication']['volume'];
  }
  else if (!empty($vars['publication']['edition'])) {
    $part_edition = ' Vol. '. $vars['publication']['edition'];
  }
  else {
    $part_edition = '';
  }

	// Issue number
	if(!empty($vars['publication']['my_issue_num'])) {
		$part_issue_num = ', Issue '. $vars['publication']['my_issue_num'];
	}
	else {
		$part_issue_num = '';
	}

	$part_issue = !empty($vars['publication']['issue_num']) ? ' No. '. $vars['publication']['issue_num'] : '';
	$part_year = t(', @year', array('@year' => $vars['publication']['year']));

	// Page
  if (!empty($vars['publication']['page_start_end'])) {
    $page_start_end = t(', pp. @page_start_end', array('@page_start_end' => $vars['publication']['page_start_end']));
  }
  else {
    $page_start_end = '';
  }

	$type_text = t(' @type_text', array('@type_text' => $vars['publication']['type_text']));

	//test
	//$output = $part_head. $part_edition. $part_issue_num. $part_year. $page_start_end. $type_text;	
	$output = $part_head. $part_edition. $part_issue_num. $part_year. $page_start_end;

	return $output;
}

/**
 * Preprocess functions for faeprofile information.
 */
function template_preprocess_faeprofile_information(&$vars) {
	// NOTE: information is a drupal user profile field
	// It is called field_profile_field, so no cache necessary.  
  $information = $vars['data'];
  $vars['information'] = $information[0]['safe_value'];
}

/**
 * Preprocess functions for faeprofile overview.
 */
function template_preprocess_faeprofile_overview(&$vars) {
  $data = '';
  $uri = $vars['uri'];
  $vars['overview'] = '';
  
  $cache_id = "faeprofile:overview:$uri:". md5($uri);
  if($cached = cache_get($cache_id, 'cache'))  {
    $data = $cached->data;
    $vars['overview'] = $data;
  }

  if(empty($data)) {
  	if(uom_fae_api_is_url_reachable()) {
			$overview = $vars['data'];
			
			if(empty($overview) || $overview == 'Empty') {
				// Clear cache only
				cache_set($cache_id, '', 'cache', time() + FAE_MODULE_CACHE_TIME);
			}
			else {
				$vars['overview'] = $overview['overviewText1']. $overview['overviewText2']. $overview['overviewText3']. $overview['overviewText4'];
			
				// Cache and backup
				$data = $vars['overview'];
				uom_fae_api_cache_and_backup($cache_id, $data);
			}
  	}
  	else {
  		// Joseki is down, so get the backup data
			$vars['overview'] = uom_fae_api_custom_cache_get($cache_id);
  	}
  }
  else {
  	// $data is above. Nothing to do here.
  }
}

/**
 * Preprocess functions for faeprofile affiliation.
 */
function template_preprocess_faeprofile_affiliations(&$vars) {
  $data = '';
  $uri = $vars['uri'];
  $vars['affiliations'] = array();
  
  $cache_id = "faeprofile:affiliation:$uri:". md5($uri);
  if($cached = cache_get($cache_id, 'cache'))  {
    $data = $cached->data;
    $vars['affiliations'] = $data;
  }
  
  if(empty($data)) {
  	if(uom_fae_api_is_url_reachable()) {
  		// We already run sparql and data is within $vars
  		// We don't run sparql here within this if statement, 
  		// so uom_fae_api_is_url_reachable is not necessary, but just put it here.
			$affiliations = $vars['data'];
			
			if(!empty($affiliations)) {
				foreach ($affiliations as $affiliation) {
					$temp = array(
						'organisation' => check_plain($affiliation['orgLabel']),
						'role' => check_plain($affiliation['roleLabel']),
					);
					$vars['affiliations'][] = theme('faeprofile_affiliation', array('affiliation' => $temp));
				}
			
				// Cache the data
				$data = $vars['affiliations'];
				uom_fae_api_cache_and_backup($cache_id, $data);
			}
			else {
				// Clear cache only
				cache_set($cache_id, '', 'cache', time() + FAE_MODULE_CACHE_TIME);
			}
  	}
 		else {
 			// Joseki is down, so get the backup data
			$vars['affiliations'] = uom_fae_api_custom_cache_get($cache_id);
 		}
  }
  else {
  	// $data is above. Nothing to do here.
  }
  
}

/**
 * Preprocess functions for faeprofile publications.
 */
function template_preprocess_faeprofile_publications(&$vars) {
	$data = '';
  $uri = $vars['uri'];
  $vars['year'] = array();

	$cache_id = "faeprofile:pub:$uri:". md5($uri);
  if($cached = cache_get($cache_id, 'cache'))  {
    $data = $cached->data;
    $vars['year'] = $data;
  }

	if(empty($data)) {
		if(uom_fae_api_is_url_reachable()) {
			$publications = $vars['data'];
		
			if(!empty($publications)) {
				foreach ($publications as $publication) {
					$datestamp = strtotime($publication['dateValue']);

					$author_text = _faeprofile_author_text($publication['article']);
					$editor_text = _faeprofile_editor_text($publication['article']);

					$page_start_end_text = _faeprofile_page_start_end($publication['article']);
					$type_array = _faeprofile_publication_type($publication['type']);

					$temp = array(
						'publication' => $publication['publication'], // e.g. published in Journal of Sport History (i.e. journal) 
						'title' => $publication['title'],
						'link' => $publication['article'],
						'type_code' => $type_array['type_code'],
						'type_text' => $type_array['type_text'],
						'publisher' => $publication['publishOrg'],
						'page_start_end' => $page_start_end_text,
						'edition' => $publication['edition'],
						'parent' => $publication['parent'],
						'volume' => $publication['volume'],
						'issue_num' => $publication['issueNum'],
						'my_issue_num' => $publication['myIssueNum'],
						'isbn13' => $publication['isbn13'],
						'date' => date('Y', $datestamp),
						'year' => date('Y', $datestamp),
						'author_text' => $author_text,
						'editor_text' => $editor_text,
					);

					$year_index = $temp['year'];
					$pub_type_index = $temp['type_text'];
					$link_index = $temp['link'];
					$vars['year'][$year_index][$pub_type_index][$link_index] = _faeprofile_publication_select_theme($temp);
				}
				krsort($vars['year']);

				// Cache and backup
				$data = $vars['year'];
				uom_fae_api_cache_and_backup($cache_id, $data);
		  }
		  else {
		  	// Clear cache only
				cache_set($cache_id, '', 'cache', time() + FAE_MODULE_CACHE_TIME);
		  }
		}
		else {
			// Joseki is down, so get the backup data
			$vars['year'] = uom_fae_api_custom_cache_get($cache_id);
		}
	}
}

/**
 * Preprocess functions for faeprofile research.
 */
function template_preprocess_faeprofile_research(&$vars) {
  $data = '';
  $uri = $vars['uri'];
  $vars['year'] = array();
  $vars['extra_grant_text'] = array();
  
  $cache_id = "faeprofile:research:$uri:". md5($uri);
  if($cached = cache_get($cache_id, 'cache'))  {
    $data = $cached->data;
    $vars['year'] = $data['year'];
    $vars['extra_grant_text'] = $data['extra_grant_text'];
  }
  
  if(empty($data)) {
  	if(uom_fae_api_is_url_reachable()) {
  		// Grant
  		// $vars doesn't contain extra_grant_text
  		$research = $vars['data'];
			if(!empty($research)) {
				foreach ($research as $grant) {
					$startstamp = strtotime($grant['dateStart']);
					$endstamp = strtotime($grant['dateEnd']);

					$vars['research'][] = array(
						'grant' => $grant['grantLabel'],
						'link' => $grant['grant'],
						'scheme' => $grant['grantScheme'],
						'role' => $grant['roleLabel'],
						'organisation' => $grant['orgLabel'],
						'start' => (!empty($startstamp)) ? date('Y', $startstamp) : '',
						'end' => (!empty($endstamp)) ? date('Y', $endstamp) : '',
					);
				}
				
				// Do some grouping of research grants.
				foreach ($vars['research'] as $grant) {
		  		$vars['year'][$grant['start']][] = theme('faeprofile_grant', array('grant' => $grant));
				}
	
				krsort($vars['year']);
			}
			
			// Extra grant
			$extra_grant_text = _faeprofile_extra_grant($uri);
			if(!empty($extra_grant_text)) {
				$vars['extra_grant_text'] = $extra_grant_text;
			}
			
			if(empty($vars['year']) && empty($vars['extra_grant_text'])) {
				// Clear cache only
				cache_set($cache_id, '', 'cache', time() + FAE_MODULE_CACHE_TIME);
			}
			else {
				// Cache and backup
				$data = $vars;
				uom_fae_api_cache_and_backup($cache_id, $data);
			}
  	}
  	else {
  		// Joseki is down, so get the backup data
			$tmp_vars = uom_fae_api_custom_cache_get($cache_id);
			$vars['year'] = $tmp_vars['year'];
    	$vars['extra_grant_text'] = $tmp_vars['extra_grant_text'];
  	}
  }
}


/**
 * Preprocess functions for faeprofile awards.
 */
function template_preprocess_faeprofile_awards(&$vars) {
	$data = '';
	$uri = $vars['uri'];
	$vars['awards'] = array();
	
	$cache_id = "faeprofile:award:$uri:". md5($uri);
  if($cached = cache_get($cache_id, 'cache'))  {
    $data = $cached->data;
    $vars['awards'] = $data;
  }
	
	if(empty($data)) {
		if(uom_fae_api_is_url_reachable()) {
			$awards = $vars['data'];
			
			if(!empty($awards)) {
				foreach ($awards as $award) {
    			$timestamp = strtotime($award['dateValue']);

					$temp = array(
						'award' => $award['awardLabel'],
						'link' => $award['award'],
						'organisation' => $award['orgLabel'],
						'year' => (!empty($timestamp)) ? date('Y', $timestamp) : '',
					);
					$tmp_array[] = $temp;
				}

				// Sort by year desc
				usort($tmp_array, function($a, $b) {
					return $b['year'] - $a['year'];
				});	

				//
				foreach($tmp_array as $element) {
					$vars['awards'][] = theme('faeprofile_award', array('award' => $element));
				}
				
				// Cache and backup
				$data = $vars['awards'];
				uom_fae_api_cache_and_backup($cache_id, $data);	
			}
			else {
				// Clear cache only
				cache_set($cache_id, '', 'cache', time() + FAE_MODULE_CACHE_TIME);
			}
		}
		else {
			// Joseki is down, so get the backup data
			$vars['awards'] = uom_fae_api_custom_cache_get($cache_id);
		}
	}
	else {
		// Nothing
	}	
}

/**
 * Preprocess functions for faeprofile linkages.
 */
function template_preprocess_faeprofile_linkages(&$vars) {
  $data = '';
  $uri = $vars['uri'];
  $vars['linkages'] = array();
  
  $cache_id = "faeprofile:linkages:$uri:". md5($uri);
  if($cached = cache_get($cache_id, 'cache'))  {
    $data = $cached->data;
    $vars['linkages'] = $data;
  }
  
  if(empty($data)) {
  	if(uom_fae_api_is_url_reachable()) {
			$linkages = $vars['data'];
			if(!empty($linkages)) {
				foreach ($linkages as $linkage) {
					$vars['linkages'][] = theme('faeprofile_linkage', array('linkage' => $linkage));
				}
				
				// Cache and backup
				$data = $vars['linkages'];
				uom_fae_api_cache_and_backup($cache_id, $data);	
			}
			else {
				// Clear cache only
				cache_set($cache_id, '', 'cache', time() + FAE_MODULE_CACHE_TIME);
			}
		}
		else {
			// Joseki is down, so get the backup data
			$vars['linkages'] = uom_fae_api_custom_cache_get($cache_id);
		}	
  }
  else {
  	// Nothing
  }
}

/**
 * Preprocess functions for faeprofile supervision.
 */
function template_preprocess_faeprofile_supervision(&$vars) {
  $data = '';
  $uri = $vars['uri'];
  $vars['available'] = array();
  $vars['supervision'] = array();
  
  $cache_id = "faeprofile:supervision:$uri:". md5($uri);
  if($cached = cache_get($cache_id, 'cache'))  {
    $data = $cached->data;
    $vars['available'] = $data['available'];
    $vars['supervision'] = $data['supervision'];
  }
  
  if(empty($data)) {
  	if(uom_fae_api_is_url_reachable()) {
  		$supervision = $vars['data'];
  		if(!empty($supervision)) {
  			$vars['available'] = theme('faeprofile_supervisor', array('available' => $supervision['supervisor']));
  			$vars['supervision'] = $supervision['supervisorText1'];
  			
  			// Cache and backup
				$data = $vars;
				uom_fae_api_cache_and_backup($cache_id, $data);
  		}
  		else {
  			// Clear cache only
				cache_set($cache_id, '', 'cache', time() + FAE_MODULE_CACHE_TIME);
  		}
  	}
  	else {
  		// Joseki is down, so get the backup data
  		$tmp_vars = uom_fae_api_custom_cache_get($cache_id);
  		$vars['available'] = $tmp_vars['available'];
  		$vars['supervision'] = $tmp_vars['supervision'];
  	}
  }
  else {
  	// Nothing
  }
  
}

/**
 * Preprocess functions for faeprofile contact.
 */
function template_preprocess_faeprofile_contact(&$vars) {
  $data = '';
  $uri = $vars['uri'];
  
  $cache_id = "faeprofile:contact:$uri:". md5($uri);
  if($cached = cache_get($cache_id, 'cache'))  {
    $data = $cached->data;
    
    $vars['email'] = $data['email'];
    $vars['phone'] = $data['phone'];
    $vars['webpage'] = $data['webpage'];
    $vars['room'] = $data['room'];
    
    $vars['building'] = $data['building'];
    $vars['supervisor'] = $data['supervisor'];
    $vars['image'] = $data['image'];
  }
  
  if(empty($data)) {
  	if(uom_fae_api_is_url_reachable()) {
  		$contact = $vars['data'];
  		
  		if(!empty($contact)) {
  			$vars['email'] = (!empty($contact['email'])) ? l($contact['email'], 'mailto:' . $contact['email']) : '';
				
				if(module_exists('unimelb_formatters')) {
					$vars['phone'] = unimelb_formatters_field_formatter_unimelb_html5_phone_link(array('value' => $contact['phone'], 'safe_value' => $contact['phone']));
				}
				else {
					$vars['phone'] = $contact['phone'];
				}
				
				$vars['webpage'] = (!empty($contact['webpage'])) ? l($contact['webpage'], $contact['webpage']) : '';
				$vars['room'] = $contact['room'];
				$vars['building'] = $contact['building'];
				$vars['supervisor'] = theme('faeprofile_supervisor', array('available'=> $contact['supervisor']));

				//$vars['image'] = theme('faeprofile_thumbnail', array('thumbnail' => $contact['thumbnail']));
				$vars['image'] = theme('faeprofile_thumbnail', array('thumbnail' => $contact['thumbnail'], 'actualFilePart' => $contact['actualFilePart']));  			

  			// Cache and backup
				$data = $vars;
				uom_fae_api_cache_and_backup($cache_id, $data);
  		}
  		else {
  			// Clear cache only
				cache_set($cache_id, '', 'cache', time() + FAE_MODULE_CACHE_TIME);
  		}
  	}
  	else {
  		// Joseki is down, so get the backup data
  		$tmp_vars = uom_fae_api_custom_cache_get($cache_id);
  		
  		$vars['email'] = $tmp_vars['email'];
		  $vars['phone'] = $tmp_vars['phone'];
		  $vars['webpage'] = $tmp_vars['webpage'];
		  $vars['room'] = $tmp_vars['room'];
		  
		  $vars['building'] = $tmp_vars['building'];
		  $vars['supervisor'] = $tmp_vars['supervisor'];
		  $vars['image'] = $tmp_vars['image'];
  	}
  }
  else {
  	// Nothing
  }
  
  
}

/**
 * Preprocess functions for faeprofile qualifications.
 */
function template_preprocess_faeprofile_qualifications(&$vars) {
	$data = '';
  $uri = $vars['uri'];
  $vars['qualifications'] = array();
  
  $cache_id = "faeprofile:qualification:$uri:". md5($uri);
  if($cached = cache_get($cache_id, 'cache'))  {
    $data = $cached->data;
    $vars['qualifications'] = $data;
  }
  
  if(empty($data)) {
  	if(uom_fae_api_is_url_reachable()) {
			$qualifications = $vars['data'];
			if(!empty($qualifications)) {
				foreach ($qualifications as $qualification) {
					$qualification['timestamp'] = strtotime($qualification['dateEnd']);
					$qualification['year'] = substr($qualification['dateEnd'], 0, 4);
					$tmp_array[] = $qualification;
				}

				// Sort by year desc
				usort($tmp_array, function($a, $b) {
					return $b['year'] - $a['year'];
				});

				// 
				foreach($tmp_array as $element) {
					$vars['qualifications'][] = theme('faeprofile_qualification', array('qualification' => $element));
				}
				
				// Cache and backup
				$data = $vars['qualifications'];
				uom_fae_api_cache_and_backup($cache_id, $data);	
			}
			else {
				// Clear cache only
				cache_set($cache_id, '', 'cache', time() + FAE_MODULE_CACHE_TIME);
			}
		}
		else {
			// Joseki is down, so get the backup data
			$vars['qualifications'] = uom_fae_api_custom_cache_get($cache_id);
		}	
  }
  else {
  	// Nothing
  }
}

/**
 * Theme a qualification.
 */
function theme_faeprofile_qualification($vars) {
  return t('@degree (@organisation, @year)', array(
    '@degree' => $vars['qualification']['degreeLabel'],
    '@organisation' => $vars['qualification']['orgLabel'],
    '@year' => date('Y', $vars['qualification']['timestamp']),
  ));
}

/**
 * Wrappers that help expose our page callbacks.
 */
function _faeprofile_account_wrapper($resource) {
  $account = stdClass();
  $account->field_fae_resource['und'][0]['url'] = $resource;
  return $account;
}

/**
 * Wrapper for the information page.
 */
function faeprofile_information_callback_wrapper($resource) {
  $account = _faeprofile_account_wrapper($resource);
  module_load_include('inc', 'faeprofile', 'faeprofile.pages');
  return faeprofile_page_information($account, FALSE);
}

/**
 * Wrapper for the overview page.
 */
function faeprofile_overview_callback_wrapper($resource) {
  $account = _faeprofile_account_wrapper($resource);
  module_load_include('inc', 'faeprofile', 'faeprofile.pages');
  return faeprofile_page_overview($account, FALSE);
}

/**
 * Wrapper for the affiliations page.
 */
function faeprofile_affiliations_callback_wrapper($resource) {
  $account = _faeprofile_account_wrapper($resource);
  module_load_include('inc', 'faeprofile', 'faeprofile.pages');
  return faeprofile_page_affiliations($account, FALSE);
}

/**
 * Wrapper for the publications page.
 */
function faeprofile_publications_callback_wrapper($resource) {
  $account = _faeprofile_account_wrapper($resource);
  module_load_include('inc', 'faeprofile', 'faeprofile.pages');
  return faeprofile_page_publications($account, FALSE);
}

/**
 * Wrapper for the research page.
 */
function faeprofile_research_callback_wrapper($resource) {
  $account = _faeprofile_account_wrapper($resource);
  module_load_include('inc', 'faeprofile', 'faeprofile.pages');
  return faeprofile_page_research($account, FALSE);
}

/**
 * Wrapper for the awards page.
 */
function faeprofile_awards_callback_wrapper($resource) {
  $account = _faeprofile_awards_wrapper($resource);
  module_load_include('inc', 'faeprofile', 'faeprofile.pages');
  return faeprofile_page_awards($account, FALSE);
}

/**
 * Wrapper for the linkages page.
 */
function faeprofile_linkages_callback_wrapper($resource) {
  $account = _faeprofile_account_wrapper($resource);
  module_load_include('inc', 'faeprofile', 'faeprofile.pages');
  return faeprofile_page_linkages($account, FALSE);
}

/**
 * Wrapper for the supervision page.
 */
function faeprofile_supervision_callback_wrapper($resource) {
  $account = _faeprofile_account_wrapper($resource);
  module_load_include('inc', 'faeprofile', 'faeprofile.pages');
  return faeprofile_page_supervision($account, FALSE);
}

/**
 * Wrapper for the contact page.
 */
function faeprofile_contact_callback_wrapper($resource) {
  $account = _faeprofile_account_wrapper($resource);
  module_load_include('inc', 'faeprofile', 'faeprofile.pages');
  return faeprofile_page_contact($account, FALSE);
}

/**
 * Wrapper for the qualifications page.
 */
function faeprofile_qualifications_callback_wrapper($resource) {
  $account = _faeprofile_account_wrapper($resource);
  module_load_include('inc', 'faeprofile', 'faeprofile.pages');
  return faeprofile_page_qualifications($account, FALSE);
}

/**
 * Implements hook_uom_fae_api_callbacks().
 */
function faeprofile_uom_fae_api_callbacks() {
  return array(
    'faeprofile_information_callback_wrapper' => t('Person: General information'),
    'faeprofile_overview_callback_wrapper' => t('Person: Overview'),
    'faeprofile_affiliations_callback_wrapper' => t('Person: Affiliations'),
    'faeprofile_publications_callback_wrapper' => t('Person: Publications'),
    'faeprofile_research_callback_wrapper' => t('Person: Research'),
    'faeprofile_awards_callback_wrapper' => t('Person: Awards'),
    'faeprofile_linkages_callback_wrapper' => t('Person: Linkages'),
    'faeprofile_supervision_callback_wrapper' => t('Person: Supervisor availability'),
    'faeprofile_contact_callback_wrapper' => t('Person: Contact information'),
    'faeprofile_qualifications_callback_wrapper' => t('Person: Qualifications'),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function faeprofile_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_ctools_plugin_api().
 *
 * If you do this, Ctools will pick up default panels pages in
 * <modulename>.pages_default.inc
 */
function faeprofile_ctools_plugin_api($module, $api) {
  if ($module == 'panels_mini' && $api == 'panels_default') {
    return array('version' => 1);
  }
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_preprocess_status_messages().
 *
 * Remove "An illegal choice has been detected. Please contact the site administrator." 
 * in exposed view filter in staff listing page. (i.e. http://site.com/about/staff)
 * https://drupal.org/node/1177882, patch doesn't fix the issue, so remove the error message instead
 */
function faeprofile_preprocess_status_messages(&$vars) {
  $messages = drupal_get_messages('error');
  if (!empty($messages['error'])) {
    $errors = $messages['error'];
    foreach ($errors as $error) {
      if ($error == t('An illegal choice has been detected. Please contact the site administrator.')) {
        continue;
      }

      drupal_set_message($error, 'error');
    }
  }
}

/**
 * Implements hook_cron().
 */
function faeprofile_cron() {
  $last_run = variable_get('faeprofile_cron', 0);

  // Early return if we don't need to run at all.
  if (empty($last_run)) {
    return;
  }

  // Next run is last run plus one week.
  $next_run = $last_run + (60 * 60 * 24 * 7);

  // If the next time we should run is in the future, exit.
  if ($next_run > time()) {
    return;
  }

  $processed = 0;
  $result = db_select('users', 'u')
    ->fields('u', array('uid'))
    ->condition('status', 0, '<>')
    ->orderBy('uid', 'ASC')
    ->execute();

  foreach ($result as $row) {
    $account = user_load($row->uid, TRUE);
    $processed += _faeprofile_update_supervisor_status($account);
  }

  // Write a log message.
  watchdog('faeprofile', 'Updated supervisor status for @count users', array('@count' => $processed), WATCHDOG_INFO);

  // Update the last run timestamp.
  variable_set('faeprofile_cron', time());
}

/**
 * Batch functions to update user's supervisor status.
 */
function faeprofile_supervision_update() {
  $batch = array(
    'operations' => array(
      array('faeprofile_supervisor_batch_process', array()),
    ),
    'finished' => 'faeprofile_supervisor_batch_finished',
    'title' => t('Updating supervisor status'),
    'init_message' => t('Updating supervisor statuses is starting'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('Supervisor status update has encountered an error.'),
    'file' => drupal_get_path('module', 'faeprofile') . '/faeprofile.batch.inc',
  );
  batch_set($batch);

  // Go back to the faeprofile admin page when done.
  batch_process('admin/config/people/faeprofile');
}

/**
 * Auto assign supervision status for each user. This funtion is called
 * via the Batch API callback.
 *
 * Use a helper to actually load and process a user, so we can call that from
 * hook_cron as well.
 *
 * @see https://drupal.org/node/180528
 */
function faeprofile_supervisor_batch_process(&$context) {
  if (!isset($context['sandbox']['progress'])) {
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['current_user'] = 0;
    $context['sandbox']['max'] = db_query('SELECT COUNT(DISTINCT uid) FROM {users} WHERE status <> 0')->fetchField();
  }

  // Process 2 users at a time only.
  $limit = 2;

  $result = db_select('users', 'u')
    ->fields('u', array('uid'))
    ->condition('uid', $context['sandbox']['current_user'], '>')
    ->condition('status', 0, '<>')
    ->orderBy('uid', 'ASC')
    ->range(0, $limit)
    ->execute();

  foreach ($result as $row) {
    $account = user_load($row->uid, TRUE);
    _faeprofile_update_supervisor_status($account);

    // Store some result for post-processing in the finished callback.
    $context['results'][] = check_plain($account->name);

    // Update our progress information.
    $context['sandbox']['progress']++;
    $context['sandbox']['current_user'] = $account->uid;
    $context['message'] = t('Now processing %user', array('%user' => $account->name));
  }

  // Inform the batch engine that we are not finished,
  // and provide an estimation of the completion level we reached.
  if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
}

/**
 * Batch 'finished' callback
 */
function faeprofile_supervisor_batch_finished($success, $results, $operations) {
  if ($success) {
    // Here we do something meaningful with the results.
    $message = count($results) .' user profiles processed.';
    drupal_set_message($message);

    // And make sure cron runs a week from now, if enabled.
    $faeprofile_cron = variable_get('faeprofile_cron', 0) ;
    if (!empty($faeprofile_cron)) {
      variable_set('faeprofile_cron', time());
    }
  }
  else {
    // An error occurred.
    // $operations contains the operations that remained unprocessed.
    $error_operation = reset($operations);
    $message = t('An error occurred while processing %error_operation with arguments: @arguments', array('%error_operation' => $error_operation[0], '@arguments' => print_r($error_operation[1], TRUE)));
    drupal_set_message($message, 'error');
  }
}

/**
 * Helper function that updates a user's supervisor status.
 *
 * @param $account
 *   A user account object.
 *
 * @return
 *   0 if the user did not have an FaE URL and 1 if it did.
 */
function _faeprofile_update_supervisor_status($account) {
  // Early return if no resource URI.
  if (empty($account->field_fae_resource[LANGUAGE_NONE][0]['url'])) {
    return 0;
  }

  $supervision = uom_fae_api_person_supervision($account->field_fae_resource[LANGUAGE_NONE][0]['url']);
  $supervision_status = (!empty($supervision) && $supervision['supervisor'] == 'Y') ? 1 : 0;
  user_save($account, $edit = array('field_person_supervision', $supervision_status));
  return 1;
}

function _faeprofile_author_text($article_uri) {
  $args = array(
  	':uri' => $article_uri,
  );
  $pub_posis = uom_fae_api_query(UOM_FAE_PUBLICATION_AUTHOR_PUB_POSIS, $args);

	//test
	//$test_pub_uri = 'http://www.findanexpert.unimelb.edu.au/individual/publication149224';

	$tmp_array = array();
  foreach($pub_posis['rows'] as $row) {
		// If we get something like:
    // - Skip http://www.findanexpert.unimelb.edu.au/individual/publication772position2
    // - Skip http://www.findanexpert.unimelb.edu.au/individual/publication772position2N
    // - We need something like http://www.findanexpert.unimelb.edu.au/individual/publication772position2Y
    if( !ctype_alpha(substr($row['pubPosi'], -1, 1)) ) {
      continue;
    }
    elseif(substr($row['pubPosi'], -1, 1) !== 'Y') {
      continue;
    }

		$tmp_person_link = uom_fae_api_query(UOM_FAE_PUBLICATION_AUTHOR_PERSON_LINK, array(':uri' => $row['pubPosi']));
		// Sometimes a pubPosi won't have a person link, due to someone forgets to put a link there.
		$person_link = $tmp_person_link['rows'][0]['personLink'];

		if(!empty($person_link)) {
			$tmp_person_name = _faeprofile_find_person_name_in_drupal($person_link);
		  if(!empty($tmp_person_name)) {
		  	$person_name = $tmp_person_name;  
		  }
		  else {
				$tmp_person_label = uom_fae_api_query(UOM_FAE_PUBLICATION_AUTHOR_NAME_LABEL, array(':uri' => $person_link));
		  	$person_name = _faeprofile_remove_title($tmp_person_label['rows'][0]['personLabel']);
		  }
		}
		else {
			// No person link, but we can use pubPosi to retrieve personLabel.
			// It will take a while, but why?
			$tmp_person_label = uom_fae_api_query(UOM_FAE_PUBLICATION_AUTHOR_NAME_LABEL_1, array(':uri' => $row['pubPosi']));
			$person_name = _faeprofile_remove_title($tmp_person_label['rows'][0]['personLabel']);
		}		

		$tmp_array[] = trim($person_name);	
	}

	$return_string = '';
  if(count($tmp_array) > 0) {
    $return_string = implode(', ', $tmp_array);
  } else {

  }

	return $return_string;
}

function _faeprofile_editor_text($article_uri) {
	$output = '';

	$editor_names = array();	
	$editor_name = '';
	$i = 1;
	// Be ware of infinite loop
	while(1) {
		$editor_uri = $article_uri. 'position'. $i. 'N';

		$args = array(
    	':uri' => $editor_uri,
    );
    $result = uom_fae_api_query(UOM_FAE_PUBLICATION_EDITOR_NAME, $args);
		$editor_name = $result['rows'][0]['editorName'];

		if(empty($editor_name)) {
    	break;
		}
		else {
			$person_name = _faeprofile_remove_title($editor_name);
			$editor_names[] = trim($person_name);
		}

		++$i;
	}

	if(count($editor_names) >= 1) {
		$output = implode(', ', $editor_names);	
	}
	else {
		$output = '';
	}

	return $output;
}

function _faeprofile_page_start_end($article_uri) {
	$output = '';	

  $args = array(
    ':uri' => $article_uri,
  );
  $result = uom_fae_api_query(UOM_FAE_PUBLICATION_PAGE_START_END, $args);

	if(count($result['rows']) > 0) {
  	$tmp_array = array();
  	foreach($result['rows'] as $row) {
 			$page_start = $row['pageStart'];
			$page_end = $row['pageEnd'];

			if(!empty($page_start) && !empty($page_end)) {
				$output .= $page_start. '-'. $page_end. ', ';
			}
			else {
				$output .= $page_start. $page_end. ', ';
			}
		}
		$output = substr($output, 0, -2);	
	}
	else {
		$output = '';
	}

	return $output;
}


/**
 * Turn a publication type URI into a label.
 */
function _faeprofile_publication_type($uri) {
	// Early return.
  if (empty($uri)) {
    return t('Other Works');
  }

  // The final two characters of the publication type uri match our array.
  $type_code = substr($uri, strlen('http://www.findanexpert.unimelb.edu.au/ontology/PublicationType'));
	$type_text = uom_fae_api_publication_types($type_code);
	$output = array('type_code' => $type_code, 'type_text' => $type_text);
  return $output; 
}

function _faeprofile_publication_select_theme($pub) {
	// NOTE: if you want to see a complete pub type list.
	// Go to

	// You are doing the whole book
	$whole_book_array = array(
		'A',
		'A1', // 'A1'  => t('Authored Research Book'),
    'A2', // 'A2'  => t('Edited Book'),
    'A3', // 'A3'  => t('Revision/New Edition'),
    'A4', // 'A4'  => t('Translated Book'),
    'A5', // 'A5'  => t('Text Book'),
    'A6', // 'A6'  => t('Authored Book (Other)'),
	);

	// You are doing chapters only
	$chapter_array = array(
		'B',
		'B1', // 'B1'  => t('Chapter in Research Book'),
    'B2', // 'B2'  => t('Chapters in Books (Other)'),
	);

	// Journal
  $journal_array = array(
		'C',
    'C1', // 'C1'  => t('Article in scholarly refereed journal'),
    'C2', // 'C2'  => t('Article in unrefereed journal (including articles in professional journals)'),
		'C3', // 'C3'  => t('Unrefereed Letter or Note'),
    'C5', // 'C5'  => t('Other refereed contribution to a refereed journal'),
  );

	// Type code
	$type_code = $pub['type_code'];
	$output = '';

	if(in_array($type_code, $whole_book_array)) {
		// Whole book
		$output = theme('faeprofile_publication_whole_book', array('publication' => $pub));			
	}
  else if(in_array($type_code, $chapter_array)) {
  	// Chapter  
		$output = theme('faeprofile_publication_chapter', array('publication' => $pub));
  }
	else if(in_array($type_code, $journal_array)) {
		// Journal
		$output = theme('faeprofile_publication_journal', array('publication' => $pub));
	}
	else {
		// Default
		$output = theme('faeprofile_publication_default', array('publication' => $pub));		
	}

	return $output;
}

function _faeprofile_remove_title($text) {
	/*
		e.g. $text = 'mr anthony gardner';
	*/

	$output = $text;

	$title_array = array(
		'mr',
		'mrs',
		'ms',
		'miss',
		'prof',
		'a\/prof', // escape
		'dr',
	);

	foreach($title_array as $element) {
		$pattern_check = '/^'. $element. '/i';
		$pattern_replace = '/'. $element. '/i';
		if(preg_match($pattern_check, $text)) {
			$output = preg_replace($pattern_replace, '', $text, 1);
			break;
		}
	}
	
	return $output;
}


function _faeprofile_extra_grant($person_uri) {
  $args = array(
    ':uri' => $person_uri,
  );
  $result = uom_fae_api_query(UOM_FAE_PERSON_EXTRA_GRANT, $args);

	// Hack
	if(empty($result)) {
		return '';
	}

	$text_array = $result['rows'][0];
	$part_1 = $part_2 = $part_3 = $part_4 = '';


	if(is_array($text_array)) {
		if(array_key_exists('extraGrantText1', $text_array)) {
			$part_1 = $text_array['extraGrantText1'];
		}

		if(array_key_exists('extraGrantText2', $text_array)) {
    	$part_2 = $text_array['extraGrantText2'];
  	} 

		if(array_key_exists('extraGrantText2', $text_array)) {
    	$part_2 = $text_array['extraGrantText2'];
  	} 

		if(array_key_exists('extraGrantText3', $text_array)) {
    	$part_3 = $text_array['extraGrantText3'];
  	}

		if(array_key_exists('extraGrantText4', $text_array)) {
    	$part_4 = $text_array['extraGrantText4'];
  	}
	}

	$return_string = $part_1. $part_2. $part_3. $part_4;

  return $return_string;
}

function _my_pub_type_compare($a, $b) {
if ($a == $b) {return 0;}
  $order= uom_fae_api_publication_types();
  $position = array_search($a,$order);
  $position2 = array_search($b, $order);

  //if both are in the $order, then sort according to their order in $order...
  if ($position2!==false && $position!==false) {return ($position < $position2) ? -1 : 1;}
  //if only one is in $order, then sort to put the one in $order first...
  if($position!==false) {return -1;}
  if($position2!==false) {return 1;}

  //if neither in $order, then a simple alphabetic sort...
  return ($a < $b) ? -1 : 1;
}


function _faeprofile_find_person_name_in_drupal($person_link = '') {
	// field_fae_resource_url is http://www.findanexpert.unimelb.edu.au/individual/person13547
	// or www.findanexpert.unimelb.edu.au/individual/person13547
	$person_link = preg_replace("(https?://)", "", $person_link);
	
	$person_name = '';
	
	$query = db_select('field_data_field_fae_resource', 'res');
	$query->join('field_data_field_profile_display_name', 'dname', 'res.entity_id = dname.entity_id');
	$query->condition('res.entity_type', 'user', '=');
	$query->condition('res.field_fae_resource_url', $person_link. '$', 'REGEXP');

  $result = $query->fields('dname', array('field_profile_display_name_value'))
    ->execute()
    ->fetchAssoc(); // Assume only 1 match

 	if(isset($result['field_profile_display_name_value']) && !empty($result['field_profile_display_name_value'])) {
  	$person_name = $result['field_profile_display_name_value'];
  }
  else {
  	$person_name = '';
  }
  return $person_name;
}
