<?php
/**
 * Overview, Affiliation, Publications, Research, Awards, Linkages, Supervision.
 */

/**
 * Helper that is used to create menu callbacks and blocks for the various elements.
 */
function faeprofile_elements() {
  return array(
    'overview' => t('Overview'),
    'affiliation' => t('Affiliation'),
    'publications' => t('Publications'),
    'research' => t('Research'),
    'awards' => t('Awards'),
    'linkages' => t('Linkages'),
    'supervision' => t('Supervision'),
    'information' => t('Information'),
    'contact' => t('Contact'),
  );
}

/**
 * Implements hook_permission().
 */
function faeprofile_permission() {
  $permissions = array();

  $permissions['administer faeprofile'] = array(
    'title' => t('Administer FaE Profile'),
    'description' => t('Choose which FaE Profile tabs are shown on user profile pages.'),
  );

  foreach (faeprofile_elements() as $element => $label) {
    $permissions['view faeprofile ' . $element] = array(
      'title' => t('View FaE @label information', array('@label' => $label)),
      'description' => t('View Find an Expert @label information on user profiles', array('@label' => $label)),
    );
  }

  return $permissions;
}

/**
 * Implements hook_menu().
 */
function faeprofile_menu() {
  $items = array();
  $weight = 0;

  $items['admin/config/people/faeprofile'] = array(
    'title' => t('FaE Profile'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('faeprofile_settings_form'),
    'access arguments' => array('administer faeprofile'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'faeprofile.admin.inc',
  );

  foreach (faeprofile_elements() as $element => $label) {
    if ($element == 'overview' || $element == 'contact') {
      continue;
    }
    $function = 'faeprofile_page_' . $element;
    $items['user/%user/' . $element] = array(
      'title' => t('@element', array('@element' => $label)),
      'page callback' => $function,
      'page arguments' => array(1),
      'access callback' => 'faeprofile_user_access',
      'access arguments' => array('view faeprofile ' . $element, 1),
      'type' => MENU_LOCAL_TASK,
      'weight' => ++$weight,
      'file' => 'faeprofile.pages.inc',
    );
  }
  return $items;
}

/**
 * Access callback for faeprofile tabs.
 *
 * Return TRUE only if a user has the correct permission and the resource
 * is present.
 */
function faeprofile_user_access($permission, $account) {
  $access = user_access($permission);

  // Seperate check for the extra profile field.
  if ($permission == 'view faeprofile information') {
    $value = trim(strip_tags($account->field_profile_profile['und'][0]['value']));
    $resource = !empty($value);
  }
  else {
    $resource = !empty($account->field_fae_resource['und'][0]['url']);
  }

  return ($access && $resource);
}

/**
 * Implements hook_menu_alter().
 */
function faeprofile_menu_alter(&$items) {
  if (variable_get('faeprofile_main', 0)) {
    $items['user/%user/view']['title'] = t('Overview');
    $items['user/%user/edit']['weight'] = 10;
  }
}

/**
 * Implements hook_block_info().
 */
function faeprofile_block_info() {
  $blocks = array();
  foreach (faeprofile_elements() as $element => $label) {
    $blocks[$element]['info'] = t('Fae Profile: @element', array('@element' => $label));
  }
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function faeprofile_block_view($delta) {
  // Only show on a user page.
  if ((arg(0) != 'user') && (count(arg()) < 2)) {
    return array();
  }

  module_load_include('inc', 'faeprofile', 'faeprofile.pages');
  $function = 'faeprofile_page_' . $delta;

  if (!function_exists($function)) {
    return array();
  }

  $account = menu_get_object('user');
  if (empty($account->field_fae_resource['und'][0]['url'])) {
    return array();
  }

  return array(
    'subject' => t('FaE Profile @delta', array('@delta' => ucwords($delta))),
    'content' => call_user_func($function, $account),
  );
}

/**
 * Implements hook_user_view().
 */
function faeprofile_user_view($account, $view_mode, $langcode) {
  if (empty($account->field_fae_resource['und'][0]['url'])) {
    return;
  }

  module_load_include('inc', 'faeprofile', 'faeprofile.pages');

  if (!function_exists('faeprofile_page_overview')) {
    return;
  }

  $account->content['faeprofile'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('@label' , array('@label' => $label)),
    '#markup' => faeprofile_page_overview($account),
    '#attributes' => array('class' => array('faeprofile-overview')),
  );
}

/**
 * Implements template_preprocess_user_profile().
 *
 * Turn off all but the overview, if required.
 */
function faeprofile_preprocess_user_profile(&$variables) {
  if (!variable_get('faeprofile_main', 0)) {
    return;
  }

  foreach (element_children($variables['user_profile']) as $element) {
    if ($element != 'faeprofile') {
      unset($variables['user_profile'][$element]);
    }
  }
}

/**
 * Implements hook_theme().
 */
function faeprofile_theme() {
  return array(
    'faeprofile_information' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-information',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_overview' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-overview',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_contact' => array(
      'variables' => array(
        'data' => array(
          'email' => '',
          'phone' => '',
          'webpage' => '',
          'room' => '',
          'building' => 'University of Melbourne',
          'supervisor' => 'N',
        ),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-contact',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_affiliation' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-affiliation',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_publications' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-publications',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_research' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-research',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_awards' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-awards',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_linkages' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-linkages',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_supervision' => array(
      'variables' => array(
        'data' => array(),
        'uri' => NULL,
      ),
      'template' => 'faeprofile-supervision',
      'path' => drupal_get_path('module', 'faeprofile') . '/templates',
    ),
    'faeprofile_image' => array(
      'variables' => array(
        'uri' => NULL,
        'style' => 'medium'
      ),
    ),
    'faeprofile_publication' => array(
      'variables' => array(
        'publication' => NULL,
      ),
    ),
    'faeprofile_grant' => array(
      'variables' => array(
        'grant' => NULL,
      ),
    ),
    'faeprofile_supervisor' => array(
      'variables' => array(
        'available' => 'N',
      ),
    ),
  );
}

/**
 * Create an image from a FaE resource URI.
 */
function theme_faeprofile_image($vars) {
  if (empty($vars['uri'])) {
    return NULL;
  }
  $ret = preg_match('/^(http:\/\/[A-Za-z0-9\.-]+)\/[a-z]+\/([a-z]+)([0-9]+)$/', $vars['uri'], $matches);
  if (!$ret) {
    return NULL;
  }
  $image = $matches[1] . '/pictures/' . $matches[3] . 'picture.jpg';

  return theme('imagecache_external', array('path' => $image, 'style_name' => $vars['style']));
}

/**
 * Theme a supervision status.
 */
function theme_faeprofile_supervisor($vars) {
  $available = $vars['available'];
  return ($vars['available'] == 'Y') ? t('<span class="supervisor-available">Available</span>') : t('<span class="supervisor-unavailable">Not available</span>');
}

/**
 * Theme an award or grant.
 */
function theme_faeprofile_grant($vars) {
  $output = t('<a href="!link">!title</a> (@scheme) awarded by @organisation', array(
    '!title' => $vars['grant']['grant'],
    '!link' => $vars['grant']['link'],
    '@scheme' => !empty($vars['grant']['scheme']) ? $vars['grant']['scheme'] . '.' : '',
    '@organisation' => $vars['grant']['organisation']
  ));

  if (!empty($vars['grant']['start'])) {
    $output .= t(' <span class="listDateTime">@start-@end</span>', array(
      '@start' => $vars['grant']['start'],
      '@end' => $vars['grant']['end'],
    ));
  }

  return $output;
}

/**
 * Theme a publication.
 */
function theme_faeprofile_publication($vars) {
  $output = t('<a href="!link">!title</a>. %publication @publisher', array(
    '!title' => $vars['publication']['title'],
    '!link' => $vars['publication']['link'],
    '%publication' => !empty($vars['publication']['publication']) ? $vars['publication']['publication'] . '.' : '',
    '@publisher' => $vars['publication']['publisher']));

  if (!empty($vars['publication']['volume'])) {
    $output .= t(' @volume', array('@volume' => $vars['publication']['volume']));
  }
  else if (!empty($vars['publication']['edition'])) {
    $output .= t(' @edition', array('@edition' => $vars['publication']['edition']));
  }

  if (!empty($vars['publication']['page_start'])) {
    $output .= t(':@start', array('@start' => $vars['publication']['page_start']));

    if (!empty($vars['publication']['page_end'])) {
      $output .= t('-@end', array('@end' => $vars['publication']['page_end']));
    }
  }

  $output .= t(' <span class="listDateTime">@year</span>', array('@year' => $vars['publication']['year']));

  return $output;
}

/**
 * Preprocess functions for faeprofile information.
 */
function template_preprocess_faeprofile_information(&$vars) {
  $information = $vars['data'];
  $vars['information'] = $information[0]['safe_value'];
}

/**
 * Preprocess functions for faeprofile overview.
 */
function template_preprocess_faeprofile_overview(&$vars) {
  $overview = $vars['data'];
  $vars['overview'] = $overview['overviewText1'];
}

/**
 * Preprocess functions for faeprofile affiliation.
 */
function template_preprocess_faeprofile_affiliation(&$vars) {
  $affiliations = $vars['data'];
  $vars['affiliations'] = array();

  foreach ($affiliations as $affiliation) {
    $vars['affiliations'][] = array(
      'organisation' => check_plain($affiliation['orgLabel']),
      'role' => check_plain($affiliation['roleLabel']),
    );
  }
}

/**
 * Preprocess functions for faeprofile publications.
 */
function template_preprocess_faeprofile_publications(&$vars) {
  $uri = $vars['uri'];
  $publications = $vars['data'];

  $vars['publications'] = array();
  $vars['year'] = array();

  foreach ($publications as $publication) {
    // dpm($publication, __FUNCTION__ . ': $publication');
    $datestamp = strtotime($publication['dateValue']);
    $vars['publications'][] = array(
      'publication' => $publication['publication'],
      'title' => $publication['title'],
      'link' => $publication['article'],
      'publisher' => $publication['publishOrg'],
      'page_start' => $publication['pageStart'],
      'page_end' => $publication['pageEnd'],
      'edition' => $publication['edition'],
      'volume' => $publication['volume'],
      'isbn13' => $publication['isbn13'],
      'date' => date('Y', $datestamp),
      'year' => date('Y', $datestamp),
    );
  }

  // Do some grouping of publications by date.
  foreach ($vars['publications'] as $publication) {
    $vars['year'][$publication['year']][] = theme('faeprofile_publication', array('publication' => $publication));
  }
  krsort($vars['year']);
}

/**
 * Preprocess functions for faeprofile research.
 */
function template_preprocess_faeprofile_research(&$vars) {
  $uri = $vars['uri'];
  $research = $vars['data'];

  $vars['research'] = array();
  $vars['grants'] = array();
  $vars['schemes'] = array();

  foreach ($research as $grant) {
    $startstamp = strtotime($grant['dateStart']);
    $endstamp = strtotime($grant['dateEnd']);

    $vars['research'][] = array(
      'grant' => $grant['grantLabel'],
      'link' => $grant['grant'],
      'scheme' => $grant['grantScheme'],
      'role' => $grant['roleLabel'],
      'organisation' => $grant['orgLabel'],
      'start' => (!empty($startstamp)) ? date('Y', $startstamp) : '',
      'end' => (!empty($endstamp)) ? date('Y', $endstamp) : '',
    );
  }

  // Do some grouping of publications by date.
  foreach ($vars['research'] as $grant) {
    $vars['grants'][] = $vars['schemes'][$grant['scheme']][] = theme('faeprofile_grant', array('grant' => $grant));
  }
  krsort($vars['schemes']);
}

/**
 * Preprocess functions for faeprofile awards.
 */
function template_preprocess_faeprofile_awards(&$vars) {
  dpm($vars, __FUNCTION__);
  $research = $vars['data'];
  $vars['research'] = t('TODO');
}

/**
 * Preprocess functions for faeprofile linkages.
 */
function template_preprocess_faeprofile_linkages(&$vars) {
  dpm($vars, __FUNCTION__);
  $linkages = $vars['data'];
  $vars['linkages'] = t('TODO');
}

/**
 * Preprocess functions for faeprofile supervision.
 */
function template_preprocess_faeprofile_supervision(&$vars) {
  $supervision = $vars['data'];
  $vars['available'] = theme_faeprofile_supervisor(array('available' => $supervision['supervisor']));
  $vars['overview'] = $supervision['supervisorText1'];
}

/**
 * Preprocess functions for faeprofile contact.
 */
function template_preprocess_faeprofile_contact(&$vars) {
  $uri = $vars['uri'];
  $contact = $vars['data'];
  unset($vars['data']);

  $vars['email'] = l($contact['email'], 'mailto:' . $contact['email']);
  $vars['phone'] = $contact['phone'];
  $vars['webpage'] = l($contact['webpage'], $contact['webpage']);
  $vars['room'] = $contact['room'];
  $vars['building'] = $contact['building'];
  $vars['supervisor'] = theme('faeprofile_supervisor', array('available'=> $contact['supervisor']));

  $vars['image'] = theme('faeprofile_image', array('uri' => $uri));
}
